### ISSUE TITLE
A slight issue with Sophia's Use Case

### ISSUE THREAD

**Issue by anastasiajiv** [anastasiajiv/Nutri-Goals#48]
For some reason, the API call doesn't work for NutrientTracked, but we are working on fixing this issue. This might have something to do with the keys or the json call.

**Comment by sophiali54** [comment]
Fixed the issue, it was something to do with my use case's controller. It was setting the names of the nutrients all lower case, while the API returned it with the first letter capitalized. They are not equal when using .equals, thus it wasn't properly detecting the nutrients. Fixed this in my controller.
